Traceback (most recent call last):
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np

N = 30

z = np.zeros((N, N))

x_array = np.linspace(-2, 2, N)
print("x_array:", x_array)
y_array = np.linspace(-2, 2, N)
print("y_array:", y_array)

for j in range(N):
    for i in range(N):
        x = x_array[i]
        y = y_array[j]
        z[i,j] = height(x, y)
    
print("z:\n", z)

plt.imshow(z)


fig = plt.figure()
ax = fig.add_subplot(projection='3d')


# Plot the surface
x1, y1 = np.meshgrid(x_array, y_array)
ax.plot_surface(x1, y1, z)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_29368\3016018927.py[0m in [0;36m<module>[1;34m[0m
[0;32m     15[0m         [0mx[0m [1;33m=[0m [0mx_array[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m     16[0m         [0my[0m [1;33m=[0m [0my_array[0m[1;33m[[0m[0mj[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 17[1;33m         [0mz[0m[1;33m[[0m[0mi[0m[1;33m,[0m[0mj[0m[1;33m][0m [1;33m=[0m [0mheight[0m[1;33m([0m[0mx[0m[1;33m,[0m [0my[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     18[0m [1;33m[0m[0m
[0;32m     19[0m [0mprint[0m[1;33m([0m[1;34m"z:\n"[0m[1;33m,[0m [0mz[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'height' is not defined
NameError: name 'height' is not defined

