Traceback (most recent call last):
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\natsciteaching\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

def r_inst(t, r_mean):
    g = 0.001
    val = r_mean * (1 + g*np.sin(2*np.pi*t/365))
    return val

r_mean = 0.01

t_vals = np.linspace(0, 365*10, 100)
r_vals = r_inst(t_vals)

plt.plot(t_vals, r_vals)




------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32mC:\Users\NATSCI~1\AppData\Local\Temp/ipykernel_11948/1314652816.py[0m in [0;36m<module>[1;34m[0m
[0;32m     10[0m [1;33m[0m[0m
[0;32m     11[0m [0mt_vals[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mlinspace[0m[1;33m([0m[1;36m0[0m[1;33m,[0m [1;36m365[0m[1;33m*[0m[1;36m10[0m[1;33m,[0m [1;36m100[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 12[1;33m [0mr_vals[0m [1;33m=[0m [0mr_inst[0m[1;33m([0m[0mt_vals[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     13[0m [1;33m[0m[0m
[0;32m     14[0m [0mplt[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mt_vals[0m[1;33m,[0m [0mr_vals[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: r_inst() missing 1 required positional argument: 'r_mean'
TypeError: r_inst() missing 1 required positional argument: 'r_mean'

