Traceback (most recent call last):
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.image as mpimg

img = mpimg.imread("25wlcatsfalling.jpg.article-962.jpg")

img2 = np.average(img, axis=2)

img2.shape

plt.imshow(img2, cmap="gray")


n, m = np.shape(img2)

x_smoothed = np.zeros((n, m))
for i in range(1, n-1):
    for j in range(1, m-1):
        x_smoothed[i, j] = np.average(img2[i-1:i+2,j-1:j+2])

plt.figure()
plt.imshow(x_smoothed, cmap="gray")

x_smoothed = np.zeros((n, m))
for i in range(2, n-2):
    for j in range(2, m-2):
        x_smoothed[i, j] = np.average(img2[i-2:i+3,j-2:j+3])

plt.figure()
plt.imshow(x_smoothed, cmap="gray")

x_smoothed = np.zeros((n, m))
for i in range(k, n-k):
    for j in range(k, m-k):
        x_smoothed[i, j] = np.average(img2[i-k:i+k+1,j-k:j+k+1])

plt.figure()
plt.imshow(x_smoothed, cmap="gray")

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_23808\3832433487.py[0m in [0;36m<module>[1;34m[0m
[0;32m     29[0m [1;33m[0m[0m
[0;32m     30[0m [0mx_smoothed[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0mzeros[0m[1;33m([0m[1;33m([0m[0mn[0m[1;33m,[0m [0mm[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 31[1;33m [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mk[0m[1;33m,[0m [0mn[0m[1;33m-[0m[0mk[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     32[0m     [1;32mfor[0m [0mj[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mk[0m[1;33m,[0m [0mm[0m[1;33m-[0m[0mk[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     33[0m         [0mx_smoothed[0m[1;33m[[0m[0mi[0m[1;33m,[0m [0mj[0m[1;33m][0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0maverage[0m[1;33m([0m[0mimg2[0m[1;33m[[0m[0mi[0m[1;33m-[0m[0mk[0m[1;33m:[0m[0mi[0m[1;33m+[0m[0mk[0m[1;33m+[0m[1;36m1[0m[1;33m,[0m[0mj[0m[1;33m-[0m[0mk[0m[1;33m:[0m[0mj[0m[1;33m+[0m[0mk[0m[1;33m+[0m[1;36m1[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'k' is not defined
NameError: name 'k' is not defined

