Traceback (most recent call last):
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\natsciteaching\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(A[0, 8])
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_10572\161630308.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mprint[0m[1;33m([0m[0mA[0m[1;33m[[0m[1;36m0[0m[1;33m,[0m [1;36m8[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mIndexError[0m: index 8 is out of bounds for axis 1 with size 8
IndexError: index 8 is out of bounds for axis 1 with size 8

